FROM python:3.12-slim

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
WORKDIR /app

COPY pyproject.toml uv.lock ./
COPY libs/ libs/
COPY backend/ backend/

RUN uv sync --frozen --no-dev

WORKDIR /app/backend
EXPOSE 8000
EXPOSE 9201

CMD ["uv", "run", "python", "-m", "backend.main"]
