"""Initial

Revision ID: ad78c1abd009
Revises: 
Create Date: 2026-09-26 16:57:20.388778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad78c1abd009'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_mappings',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('tr_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_mappings_tr_id'), 'device_mappings', ['tr_id'], unique=False)
    op.create_index(op.f('ix_device_mappings_unit_id'), 'device_mappings', ['unit_id'], unique=True)
    op.create_table('prediction_logs',
    sa.Column('tr_id', sa.Integer(), nullable=False),
    sa.Column('predicted_delay_s', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('pattern_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_logs_tr_id'), 'prediction_logs', ['tr_id'], unique=False)
    op.create_table('schedule_plans',
    sa.Column('tr_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.BigInteger(), nullable=False),
    sa.Column('time_begin', sa.DateTime(timezone=True), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedule_plans_stop_id'), 'schedule_plans', ['stop_id'], unique=False)
    op.create_index(op.f('ix_schedule_plans_time_begin'), 'schedule_plans', ['time_begin'], unique=False)
    op.create_index(op.f('ix_schedule_plans_tr_id'), 'schedule_plans', ['tr_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_plans_tr_id'), table_name='schedule_plans')
    op.drop_index(op.f('ix_schedule_plans_time_begin'), table_name='schedule_plans')
    op.drop_index(op.f('ix_schedule_plans_stop_id'), table_name='schedule_plans')
    op.drop_table('schedule_plans')
    op.drop_index(op.f('ix_prediction_logs_tr_id'), table_name='prediction_logs')
    op.drop_table('prediction_logs')
    op.drop_index(op.f('ix_device_mappings_unit_id'), table_name='device_mappings')
    op.drop_index(op.f('ix_device_mappings_tr_id'), table_name='device_mappings')
    op.drop_table('device_mappings')
    # ### end Alembic commands ###
